--[[
    init.lua
    Created: 03/20/2023 23:41:27
    Description: Autogenerated script file for the map tutorial_zone.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local tutorial_zone = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---tutorial_zone.Init(zone)
--Engine callback function
function tutorial_zone.Init(zone)


end

---tutorial_zone.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function tutorial_zone.EnterSegment(zone, rescuing, segmentID, mapID)


end

---tutorial_zone.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function tutorial_zone.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---tutorial_zone.Rescued(zone, name, mail)
--Engine callback function
function tutorial_zone.Rescued(zone, name, mail)


end

return tutorial_zone

