--[[
    init.lua
    Created: 04/12/2023 15:20:44
    Description: Autogenerated script file for the map large_lake.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local large_lake = {}


-------------------------------
-- Map Callbacks
-------------------------------
---large_lake.Init(map)
--Engine callback function
function large_lake.Init(map)


end

---large_lake.Enter(map)
--Engine callback function
function large_lake.Enter(map)
  
  local player = CH("PLAYER")
  local enemy = CH("Croco")
  
  GAME:CutsceneMode(true)
  
  UI:WaitShowTitle(GAME:GetCurrentGround().Name:ToLocal(), 20)
  GAME:WaitFrames(30)
  UI:WaitHideTitle(20)
  
  GAME:MoveCamera(180, 172, 1, false)
  
  GAME:FadeIn(20)
  
  GROUND:MoveToPosition(player, 172, 192, false, 2)
  
  SOUND:PlayBGM("", false)
  GROUND:CharSetEmote(player, "exclaim", 1)
  
  UI:SetSpeaker(STRINGS:Format("\\uE040"))
  UI:WaitShowDialogue("Stop right there!")
  
  SOUND:PlayBattleSE("DUN_Aqua_Tail")
  
  local emitter = RogueEssence.Content.SingleEmitter(RogueEssence.Content.AnimData("Aqua_Tail_Splash", 3))
  emitter.LocHeight = 8
  GROUND:PlayVFX(emitter, enemy.Bounds.Center.X, enemy.Bounds.Center.Y)
  
  GROUND:Unhide("Croco")
  
  GAME:WaitFrames(60)
  
  SOUND:PlayBGM("A13. Threat.ogg", false)
  
  UI:SetSpeaker(enemy)
  UI:WaitShowDialogue("I dunno who you are,[pause=30] but yer on my property!")
  UI:WaitShowDialogue("Didn't ya read the sign?")
  UI:SetSpeakerEmotion("Angry")
  UI:WaitShowDialogue("Trespassers[pause=0] get chomped!")
  
  SOUND:PlayBattleSE("EVT_Roar")
  GROUND:CharSetAnim(enemy, "Shoot", false)
  
  GAME:WaitFrames(30)
  
  COMMON.BossTransition()
  
  GAME:CutsceneMode(false)
  
  GAME:ContinueDungeon('large_woods', 1, 0, 0)
end

---large_lake.Exit(map)
--Engine callback function
function large_lake.Exit(map)


end

---large_lake.Update(map)
--Engine callback function
function large_lake.Update(map)


end

---large_lake.GameSave(map)
--Engine callback function
function large_lake.GameSave(map)


end

---large_lake.GameLoad(map)
--Engine callback function
function large_lake.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return large_lake

