--[[
    init.lua
    Created: 03/23/2023 21:53:31
    Description: Autogenerated script file for the map rescue_team_base.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local rescue_team_base = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---rescue_team_base.Init(map)
--Engine callback function
function rescue_team_base.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  

end

---rescue_team_base.Enter(map)
--Engine callback function
function rescue_team_base.Enter(map)

  GAME:FadeIn(20)

end

---rescue_team_base.Exit(map)
--Engine callback function
function rescue_team_base.Exit(map)


end

---rescue_team_base.Update(map)
--Engine callback function
function rescue_team_base.Update(map)


end

---rescue_team_base.GameSave(map)
--Engine callback function
function rescue_team_base.GameSave(map)


end

---rescue_team_base.GameLoad(map)
--Engine callback function
function rescue_team_base.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function rescue_team_base.Exit_Base_Touch(obj, activator)
  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("rescue_team_base_inside", "Base_Exit")
end

function rescue_team_base.Mailbox_Action(obj, activator)
  UI:ResetSpeaker()
  UI:SetAutoFinish(true)
  UI:WaitShowDialogue("The mailbox is empty.")
end

function rescue_team_base.Friend_Sign_Action(obj, activator)
  COMMON.ShowTeamAssemblyMenu(obj, COMMON.RespawnAllies)
end

function rescue_team_base.South_Exit_Touch(obj, activator)
  local dungeon_entrances = { "large_woods" }
  local ground_entrances = { }
  COMMON.ShowDestinationMenu(dungeon_entrances, ground_entrances)
end

function rescue_team_base.Friend_Action(obj, activator)
  local npc = CH('Friend') --obtain the NPC
  UI:SetSpeaker(npc) --set it to the dialogue box
  GROUND:CharTurnToChar(npc, activator)
  UI:WaitShowDialogue(STRINGS:Format("Hello, {0}!", activator:GetDisplayName()))
  COMMON.UnlockWithFanfare("large_woods", false)
end


return rescue_team_base

